openapi: 3.0.0
info:
  title: Example API
  version: 1.0.0
  description: A simple example of OpenAPI 3 documentation

paths:
  /users:
    get:
      summary: Retrieve a list of users
      responses:
        "200":
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: John Doe
